import { LOCAL_RELAY_SRC } from "./config";
import { sanitizeToolName } from "./names";
import type {
  EmbedManifest,
  ScanJob,
  SelectedTool,
  ToolCandidate,
} from "./types";

export function applySelection(
  job: ScanJob,
  selected: SelectedTool[] | undefined
): ToolCandidate[] {
  const byId = new Map(job.candidates.map((c) => [c.id, c]));
  const used = new Set<string>();
  const source = selected?.length
    ? selected
    : job.candidates.map((c) => ({
        id: c.id,
        name: c.name,
        description: c.description,
        enabled: true,
      }));

  const out: ToolCandidate[] = [];
  for (const sel of source) {
    if (sel.enabled === false) continue;
    const base = byId.get(sel.id);
    if (!base) continue;
    const name = sanitizeToolName(sel.name || base.name, used);
    out.push({
      ...base,
      name,
      description: (sel.description || base.description).trim() || base.description,
      enabled: true,
    });
  }
  return out;
}

export function buildManifest(
  job: ScanJob,
  tools: ToolCandidate[],
  includeLocalRelay: boolean
): EmbedManifest {
  return {
    name: "webmcp-forge",
    version: "1.0.0",
    generatedAt: new Date().toISOString(),
    siteUrl: job.url,
    origin: job.origin,
    includeLocalRelay,
    localRelaySrc: LOCAL_RELAY_SRC,
    polyfill: {
      prefer: "document.modelContext",
      fallback: "navigator.modelContext",
      note: "Registers on document.modelContext with navigator.modelContext fallback. Compatible with @mcp-b/webmcp-polyfill and native Chrome. Optional @mcp-b/webmcp-local-relay embed.js for Cursor / Claude Desktop.",
    },
    tools,
  };
}

export function generateEmbedJs(manifest: EmbedManifest): string {
  return `${EMBED_RUNTIME_PREFIX}\n  var MANIFEST = ${JSON.stringify(manifest)};\n${EMBED_RUNTIME_BODY}`;
}

const EMBED_RUNTIME_PREFIX = `/* webmcp-forge.embed.js — generated by WebMCP Forge
 * Tools run in the visitor's open tab (cookies, auth, live DOM).
 * Prefers document.modelContext, falls back to navigator.modelContext,
 * and installs a small polyfill if neither exists.
 */
(function WebMcpForgeEmbed(global) {
  "use strict";`;

const EMBED_RUNTIME_BODY = `
  function waitForDom() {
    if (document.readyState === "complete" || document.readyState === "interactive") {
      return Promise.resolve();
    }
    return new Promise(function (resolve) {
      document.addEventListener("DOMContentLoaded", resolve, { once: true });
    });
  }

  function installPolyfill() {
    var existing = document.modelContext || navigator.modelContext;
    if (existing && typeof existing.registerTool === "function") {
      if (!document.modelContext) {
        try {
          Object.defineProperty(document, "modelContext", {
            configurable: true,
            get: function () { return existing; }
          });
        } catch (e) {
          document.modelContext = existing;
        }
      }
      return existing;
    }

    var registry = Object.create(null);
    var ctx = new EventTarget();

    ctx.registerTool = function (tool, options) {
      if (!tool || typeof tool.name !== "string" || !tool.name) {
        return Promise.reject(new TypeError("registerTool(tool) requires a non-empty name"));
      }
      if (typeof tool.description !== "string" || !tool.description) {
        return Promise.reject(new TypeError("registerTool(tool) requires a non-empty description"));
      }
      if (typeof tool.execute !== "function") {
        return Promise.reject(new TypeError("registerTool(tool) requires execute"));
      }
      if (registry[tool.name]) {
        return Promise.reject(new Error("Duplicate tool: " + tool.name));
      }
      registry[tool.name] = tool;
      if (options && options.signal) {
        options.signal.addEventListener("abort", function () {
          delete registry[tool.name];
          ctx.dispatchEvent(new Event("toolchange"));
        });
      }
      ctx.dispatchEvent(new Event("toolchange"));
      return Promise.resolve();
    };

    ctx.getTools = function () {
      return Promise.resolve(
        Object.keys(registry)
          .sort()
          .map(function (name) {
            var t = registry[name];
            return {
              name: t.name,
              title: t.title || t.name,
              description: t.description,
              inputSchema: t.inputSchema || { type: "object", properties: {} },
              origin: location.origin,
              window: window
            };
          })
      );
    };

    ctx.executeTool = function (toolOrName, inputJson) {
      var name = typeof toolOrName === "string" ? toolOrName : toolOrName && toolOrName.name;
      var tool = registry[name];
      if (!tool) return Promise.reject(new Error("Unknown tool: " + name));
      var args = {};
      try {
        if (typeof inputJson === "string" && inputJson.trim()) args = JSON.parse(inputJson);
        else if (inputJson && typeof inputJson === "object") args = inputJson;
      } catch (e) {
        return Promise.reject(e);
      }
      return Promise.resolve(tool.execute(args));
    };

    try {
      Object.defineProperty(document, "modelContext", {
        configurable: true,
        get: function () { return ctx; }
      });
    } catch (e) {
      document.modelContext = ctx;
    }
    try {
      if (!navigator.modelContext) {
        Object.defineProperty(navigator, "modelContext", {
          configurable: true,
          get: function () { return ctx; }
        });
      }
    } catch (e2) { /* ignore */ }
    return ctx;
  }

  function queryFirst(selectors) {
    var list = Array.isArray(selectors) ? selectors : [selectors];
    for (var i = 0; i < list.length; i++) {
      if (!list[i]) continue;
      try {
        var el = document.querySelector(list[i]);
        if (el) return el;
      } catch (e) { /* bad selector */ }
    }
    return null;
  }

  function queryAll(selectors) {
    var out = [];
    var list = Array.isArray(selectors) ? selectors : [selectors];
    for (var i = 0; i < list.length; i++) {
      if (!list[i]) continue;
      try {
        document.querySelectorAll(list[i]).forEach(function (el) {
          if (out.indexOf(el) === -1) out.push(el);
        });
      } catch (e) { /* bad selector */ }
    }
    return out;
  }

  function setFieldValue(el, value) {
    if (!el) return;
    var tag = el.tagName.toLowerCase();
    if (tag === "select") {
      el.value = value;
    } else if (el.type === "checkbox" || el.type === "radio") {
      el.checked = Boolean(value) && value !== "false" && value !== "0";
    } else {
      var proto = el.tagName === "TEXTAREA"
        ? window.HTMLTextAreaElement.prototype
        : window.HTMLInputElement.prototype;
      var desc = Object.getOwnPropertyDescriptor(proto, "value");
      if (desc && desc.set) desc.set.call(el, value == null ? "" : String(value));
      else el.value = value == null ? "" : String(value);
    }
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }

  function wrap(data) {
    var text = typeof data === "string" ? data : JSON.stringify(data, null, 2);
    return { content: [{ type: "text", text: text }], data: data };
  }

  function executeImpl(tool, args) {
    args = args || {};
    switch (tool.kind) {
      case "get_page_info": {
        return wrap({
          title: document.title,
          url: location.href,
          description: (document.querySelector('meta[name="description"]') || {}).content || "",
          headings: Array.prototype.slice.call(document.querySelectorAll("h1,h2,h3"), 0, 20).map(function (h) {
            return (h.textContent || "").replace(/\\s+/g, " ").trim();
          })
        });
      }
      case "get_site_nav": {
        var navSel = (tool.selectors && tool.selectors.nav) || "nav a[href], [role='navigation'] a[href], header a[href]";
        var navLinks = queryAll(navSel).map(function (a) {
          return { text: (a.textContent || "").replace(/\\s+/g, " ").trim(), href: a.href, path: a.pathname };
        });
        return wrap({ links: navLinks });
      }
      case "list_links": {
        var limit = typeof args.limit === "number" ? args.limit : 80;
        var origin = location.origin;
        var links = Array.prototype.slice.call(document.querySelectorAll("a[href]"), 0, limit).map(function (a) {
          return { text: (a.textContent || "").replace(/\\s+/g, " ").trim().slice(0, 120), href: a.href };
        });
        return wrap({
          count: links.length,
          links: links,
          sameOrigin: links.filter(function (l) { return l.href.indexOf(origin) === 0; })
        });
      }
      case "list_products": {
        var cards = queryAll((tool.selectors && tool.selectors.product) || ".product-card, [data-product], [itemtype*='Product']");
        var products = cards.map(function (card) {
          var titleEl = card.querySelector("h2,h3,.product-title,[itemprop='name']") || card;
          var priceEl = card.querySelector(".price,[itemprop='price'],[data-price],.product-price");
          var link = card.querySelector("a[href]");
          return {
            title: (titleEl.textContent || "").replace(/\\s+/g, " ").trim().slice(0, 160),
            price: priceEl ? (priceEl.textContent || "").replace(/\\s+/g, " ").trim() : undefined,
            href: link ? link.href : undefined
          };
        }).filter(function (p) { return p.title; });
        return wrap({ products: products, count: products.length });
      }
      case "fill_form": {
        var form = queryFirst(tool.selectors && tool.selectors.form);
        if (!form) return wrap({ ok: false, error: "Form not found", selector: tool.selectors && tool.selectors.form });
        var fields = args.fields || {};
        var filled = [];
        var fieldDefs = (tool.metadata && tool.metadata.fields) || [];
        fieldDefs.forEach(function (fd) {
          var value = fields[fd.name];
          if (value == null) return;
          var el = (fd.selector && form.querySelector(fd.selector)) || form.querySelector('[name="' + fd.name + '"]');
          if (el) {
            setFieldValue(el, value);
            filled.push({ name: fd.name, value: String(value) });
          }
        });
        Object.keys(fields).forEach(function (name) {
          if (filled.some(function (f) { return f.name === name; })) return;
          var el2 = form.querySelector('[name="' + name + '"]');
          if (el2) {
            setFieldValue(el2, fields[name]);
            filled.push({ name: name, value: String(fields[name]) });
          }
        });
        var dryRun = args.dryRun !== false;
        var confirmSubmit = args.confirmSubmit === true;
        var submitted = false;
        if (!dryRun && confirmSubmit) {
          if (typeof form.requestSubmit === "function") form.requestSubmit();
          else form.submit();
          submitted = true;
        }
        return wrap({
          ok: true,
          filled: filled,
          dryRun: dryRun,
          submitted: submitted,
          note: submitted
            ? "Form submitted"
            : "Form filled without submit. Pass dryRun:false and confirmSubmit:true to submit."
        });
      }
      case "search_on_page": {
        var input = queryFirst(tool.selectors && tool.selectors.search);
        if (!input) {
          input = document.querySelector('input[type="search"], input[name*="search" i], input[placeholder*="search" i]');
        }
        if (!input) return wrap({ ok: false, error: "Search input not found" });
        if (!args.query) return wrap({ ok: false, error: "query is required" });
        setFieldValue(input, args.query);
        var submittedSearch = false;
        if (args.submit === true) {
          var sform = input.form;
          if (sform && typeof sform.requestSubmit === "function") {
            sform.requestSubmit();
            submittedSearch = true;
          } else {
            input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }));
            submittedSearch = true;
          }
        }
        return wrap({ ok: true, query: args.query, submitted: submittedSearch, value: input.value });
      }
      case "click_by_text": {
        var needle = String(args.text || "").trim().toLowerCase();
        if (!needle) return wrap({ ok: false, error: "text is required" });
        var nodes = Array.prototype.slice.call(
          document.querySelectorAll('a, button, [role="button"], input[type="submit"], input[type="button"]')
        );
        var match = nodes.find(function (el) {
          var t = ((el.textContent || el.value || el.getAttribute("aria-label") || "")).replace(/\\s+/g, " ").trim().toLowerCase();
          return t === needle || t.indexOf(needle) !== -1;
        });
        if (!match) return wrap({ ok: false, error: "No clickable element matching text", text: args.text });
        match.click();
        return wrap({
          ok: true,
          clicked: true,
          text: ((match.textContent || match.value || "") + "").replace(/\\s+/g, " ").trim().slice(0, 80),
          tag: match.tagName.toLowerCase()
        });
      }
      case "open_path": {
        var path = args.path;
        var allowed = (tool.metadata && tool.metadata.allowlist) || [];
        if (!path) return wrap({ ok: false, error: "path is required", allowlist: allowed });
        var ok = allowed.some(function (p) {
          var a = String(p).replace(/\\/$/, "") || "/";
          var b = String(path).replace(/\\/$/, "") || "/";
          return a === b || p === path;
        });
        if (!ok) return wrap({ ok: false, error: "path is not allowlisted", path: path, allowlist: allowed });
        var url = String(path).indexOf("http") === 0 ? path : location.origin + (String(path).charAt(0) === "/" ? path : "/" + path);
        location.assign(url);
        return wrap({ ok: true, navigating: url });
      }
      default:
        return wrap({ ok: false, error: "Unknown tool kind", kind: tool.kind });
    }
  }

  function loadLocalRelay() {
    if (!MANIFEST.includeLocalRelay) return;
    var src = MANIFEST.localRelaySrc || "https://cdn.jsdelivr.net/npm/@mcp-b/webmcp-local-relay@latest/dist/browser/embed.js";
    if (document.querySelector('script[data-webmcp-local-relay="1"]')) return;
    var s = document.createElement("script");
    s.src = src;
    s.async = true;
    s.setAttribute("data-webmcp-local-relay", "1");
    document.documentElement.appendChild(s);
    console.log("[WebMCP Forge] loading local-relay embed");
  }

  function boot() {
    return waitForDom().then(function () {
      var ctx = installPolyfill();
      var tools = MANIFEST.tools || [];
      var chain = Promise.resolve();
      tools.forEach(function (tool) {
        chain = chain.then(function () {
          return ctx.registerTool({
            name: tool.name,
            description: tool.description,
            inputSchema: tool.inputSchema || { type: "object", properties: {} },
            execute: function (input) { return executeImpl(tool, input); }
          }).then(function () {
            console.log("[WebMCP Forge] registered:", tool.name);
          }).catch(function (err) {
            console.warn("[WebMCP Forge] failed to register", tool.name, err);
          });
        });
      });
      return chain.then(function () {
        loadLocalRelay();
        return ctx;
      });
    });
  }

  var ready = boot();
  global.__WEBMCP_FORGE_READY__ = ready;
  global.__WEBMCP_FORGE_MANIFEST__ = MANIFEST;
})(typeof window !== "undefined" ? window : this);
//# sourceURL=webmcp-forge.embed.js
`;
